### ISSUE TITLE
Incorrect output regex on certain inputs.

### ISSUE THREAD

**Issue by IQuick143** [ZhukovAlexander/triegex#7]
When the words fed into the trie are a prefix of an other word, the regex outputted is not correct.

Example code used to reproduce bug:

```Python
import triegex

def RegexFromList(listOfWords):
	t = triegex.Triegex()
	for i in listOfWords:
		t.add(i)
	return t.to_regex()

print(RegexFromList(["TEST", "TE", "TEXT", "BANANA"]))
```

This code outputs: `(?:XT\b|TE\b|~^(?#match nothing))`
Which happens to match `TE` correctly but matches `XT` too and doesn't match `TEXT, TEST, BANANA` as would be expected.

Expected Regex would be: `(?:TE(?:\b|XT\b|ST\b)|BANANA\b|~^(?#match nothing))` or equivalent.

**Comment by IQuick143** [comment]
I've written a fix for this bug but it involves rewriting the whole TrierexNode.to_regex() method and my implementation is recursive (but very simple), all unit tests pass.

Is the recursion okay, or must I rewrite it into a loop? (not trivial in this case)

**Comment by IQuick143** [comment]
Either way I've written a recursive implementation

**Comment by IQuick143** [comment]
Either way I've made an iterative implementation.

**Comment by ZhukovAlexander** [comment]
@IQuick143 thanks for your work, I'll release the new version to PyPI as soon as I can.
